openapi: 3.0.3
info:
  title: Order creator
  description: Order creator
  version: 1.0.0
tags:
  - name: orders
paths:
  /orders:
    post:
      tags:
        - orders
      description: Creates an order
      operationId: createOrders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order-request-dto'
      responses:
        '201':
          description: The order has been created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order-response-dto'

components:
  schemas:
    order-request-dto:
      title: OrderRequestDto
      type: object
      properties:
        orderName:
          type: string
          minLength: 1
          maxLength: 50
          example: new Order
        quantity:
          type: integer
          minLength: 1
          maxLength: 100
          example: 1
        price:
          type: integer
          minLength: 1
          example: 100
        priority:
          type: integer
          minLength: 1
          maxLength: 5
          example: 1
    order-response-dto:
      title: OrderResponseDto
      type: object
      properties:
        orderName:
          type: string
          minLength: 1
          maxLength: 50
          example: new Order
        orderId:
          type: string
          minLength: 1
          maxLength: 36
          example: 00000000-0000-0000-c000-000000000001
        quantity:
          type: integer
          minLength: 1
          maxLength: 100
          example: 1
        price:
          type: integer
          minLength: 1
          example: 100
        priority:
          type: integer
          minLength: 1
          maxLength: 5
          example: 1