# This is a basic workflow to help you get started with Actions

name: order-creator-CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: order_creator
          postgresql user: user
          postgresql password: pass

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Maven deploy, make sure you have correct configurations in your pom.xml
      - name: deploy to Azure Spring Apps using Maven
        run: |
          mvn azure-spring-apps:deploy