# This is a basic workflow to help you get started with Actions

name: order-creator-CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2

      - name: SecureStack All-In-One GitHub Action
        uses: SecureStackCo/actions-all-in-one@v0.1.2
        with:
          # SecureStack API key - generate an API key at https://app.securestack.com
          securestack_api_key: ${{ secrets.SECURESTACK_API_KEY }}
          # SecureStack Application ID - can be retrieved by accessing required application at https://app.securestack.com
          securestack_app_id: ${{ secrets.SECURESTACK_APP_ID }}
          # Severities lower than this value will be reported in the workflow console but will not cause an error for the action; value should be one of: critical | high | medium | low
          severity:   high
